-- demo data for the product database table (electronics store)
INSERT INTO product (name, category, inventory_count) VALUES ('4K OLED TV', 'Televisions', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Wireless Earbuds', 'Audio', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Thermostat', 'Smart Home', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Ultrabook Laptop', 'Laptops', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('Android Flagship Phone', 'Smartphones', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('Soundbar with Subwoofer', 'Audio', 5);
INSERT INTO product (name, category, inventory_count) VALUES ('55" QLED TV', 'Televisions', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Light Bulb Pack', 'Smart Home', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Gaming Laptop', 'Laptops', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Foldable Smartphone', 'Smartphones', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('Bluetooth Speaker', 'Audio', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('65" Mini-LED TV', 'Televisions', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Doorbell', 'Smart Home', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('2-in-1 Convertible Laptop', 'Laptops', 5);
INSERT INTO product (name, category, inventory_count) VALUES ('Budget Android Phone', 'Smartphones', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Noise-Canceling Headphones', 'Audio', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('75" 4K LED TV', 'Televisions', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Plug 4-Pack', 'Smart Home', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('Creator Laptop', 'Laptops', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('iOS Flagship Phone', 'Smartphones', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('Bookshelf Speakers', 'Audio', 5);
INSERT INTO product (name, category, inventory_count) VALUES ('50" 4K TV', 'Televisions', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Display', 'Smart Home', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Portable Chromebook', 'Laptops', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Midrange Android Phone', 'Smartphones', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('Record Player with Bluetooth', 'Audio', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('8K QLED TV', 'Televisions', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Home Hub', 'Smart Home', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('Business Laptop', 'Laptops', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Rugged Smartphone', 'Smartphones', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Studio Headphones', 'Audio', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('43" UHD TV', 'Televisions', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Air Purifier', 'Smart Home', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Entry Gaming Laptop', 'Laptops', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('Camera-Centric Phone', 'Smartphones', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Wireless Speaker Duo', 'Audio', 5);
INSERT INTO product (name, category, inventory_count) VALUES ('Portable Projector', 'Televisions', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Leak Sensor', 'Smart Home', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('Student Laptop Bundle', 'Laptops', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('Compact Smartphone', 'Smartphones', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Vinyl-Friendly Speakers', 'Audio', 6);
INSERT INTO product (name, category, inventory_count) VALUES ('60" Plasma TV', 'Televisions', 1);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Security Camera', 'Smart Home', 5);
INSERT INTO product (name, category, inventory_count) VALUES ('Workstation Laptop', 'Laptops', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('5G Budget Phone', 'Smartphones', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Dolby Atmos Soundbar', 'Audio', 4);
INSERT INTO product (name, category, inventory_count) VALUES ('Curved Gaming TV', 'Televisions', 3);
INSERT INTO product (name, category, inventory_count) VALUES ('Smart Garage Opener', 'Smart Home', 0);
INSERT INTO product (name, category, inventory_count) VALUES ('Lightweight Laptop', 'Laptops', 2);
INSERT INTO product (name, category, inventory_count) VALUES ('Flagship Android Pro', 'Smartphones', 6);
